local _OBJ = {
	place = {
		["START"]	= { next1 = "A", },
		["A"]		= { isPlaced = false, tile = nil, next1 = "A1", next2 = "HZF1", },
		["A1"] 		= { isPlaced = false, tile = nil, next1 = "A2", },
		["A2"] 		= { isPlaced = false, tile = nil, next1 = "A3", },
		["A3"] 		= { isPlaced = false, tile = nil, next1 = "B", },
		["HZF1"]	= { isPlaced = false, tile = nil, next1 = "HZF2", },
		["HZF2"] 	= { isPlaced = false, tile = nil, next1 = "HZF3", },
		["HZF3"] 	= { isPlaced = false, tile = nil, next1 = "HZF4", },
		["HZF4"] 	= { isPlaced = false, tile = nil, next1 = "HZFA1", },
		["HZFA1"] 	= { isPlaced = false, tile = nil, next1 = "HZFA2", addAct = TODO, },
		["HZFA2"] 	= { isPlaced = false, tile = nil, next1 = "B", addAct = TODO, },
		["B"] 		= { isPlaced = false, tile = nil, next1 = "B1", next2 = "HZD1" },
		["B1"] 		= { isPlaced = false, tile = nil, next1 = "B2", bush = true, },
		["B2"] 		= { isPlaced = false, tile = nil, next1 = "B3", },
		["B3"] 		= { isPlaced = false, tile = nil, next1 = "C", },
		["HZD1"] 	= { isPlaced = false, tile = nil, next1 = "HZD2", },
		["HZD2"] 	= { isPlaced = false, tile = nil, next1 = "HZD3", },
		["HZD3"] 	= { isPlaced = false, tile = nil, next1 = "HZD4", },
		["HZD4"] 	= { isPlaced = false, tile = nil, next1 = "HZDB1", },
		["HZDB1"] 	= { isPlaced = false, tile = nil, next1 = "C", addAct = TODO, },
		["C"] 		= { isPlaced = false, tile = nil, next1 = "C1", next2 = "T", },
		["C1"] 		= { isPlaced = false, tile = nil, next1 = "C2", bush = true, },
		["C2"] 		= { isPlaced = false, tile = nil, next1 = "E", bush = true, },
		["T"] 		= { isPlaced = false, tile = nil, next1 = "D", next2 = "TP1", },
		["D"] 		= { isPlaced = false, tile = nil, next1 = "E", },
		["TP1"] 	= { isPlaced = false, tile = nil, next1 = "TP2", },
		["TP2"] 	= { isPlaced = false, tile = nil, next1 = "TP3", },
		["TP3"] 	= { isPlaced = false, tile = nil, next1 = "TP4", },
		["TP4"] 	= { isPlaced = false, tile = nil, next1 = "TP5", },
		["TP5"] 	= { isPlaced = false, tile = nil, next1 = "TP6", },
		["TP6"] 	= { isPlaced = false, tile = nil, next1 = "TPT1", },
		["TPT1"] 	= { isPlaced = false, tile = nil, next1 = "TPT2", addAct = true, },
		["TPT2"] 	= { isPlaced = false, tile = nil, next1 = "E", addAct = true, },
		["E"] 		= { isPlaced = false, tile = nil, next1 = "E1", next2 = "HZR1", },
		["E1"] 		= { isPlaced = false, tile = nil, next1 = "E2", bush = true, },
		["E2"] 		= { isPlaced = false, tile = nil, next1 = "F", bush = true, },
		["HZR1"] 	= { isPlaced = false, tile = nil, next1 = "HZR2", },
		["HZR2"] 	= { isPlaced = false, tile = nil, next1 = "HZR3", },
		["HZR3"] 	= { isPlaced = false, tile = nil, next1 = "HZR4", },
		["HZR4"] 	= { isPlaced = false, tile = nil, next1 = "HZRE1", },
		["HZRE1"] 	= { isPlaced = false, tile = nil, next1 = "HZRE2", addAct = TODO, },
		["HZRE2"] 	= { isPlaced = false, tile = nil, next1 = "F", addAct = TODO, },
		["F"] 		= { isPlaced = false, tile = nil, next1 = "F1", next2 = "F2", },
		["F1"] 		= { isPlaced = false, tile = nil, next1 = "G", bush = true, },
		["F2"] 		= { isPlaced = false, tile = nil, next1 = "G", },
		["G"] 		= { isPlaced = false, tile = nil, next1 = "G1", next2 = "G2", },
		["G1"] 		= { isPlaced = false, tile = nil, next1 = "KC", },
		["G2"] 		= { isPlaced = false, tile = nil, next1 = "KC", },
		["KC"]		= { },
	},
	building = {
		["A"] = { },
		["B"] = { },
		["C"] = { },
		["D"] = { },
		["E"] = { },
		["F"] = { },
		["G"] = { },
	},
	actions = {
		["1D"] = {text = "Gain 1 dollars", act = nil}, 
		["2D"] = {text = "Gain 2 dollars", act = nil}, 
		["4D"] = {text = "Gain 4 dollars", act = nil}, 
		["D_D"] = {text = "Draw 1 and discard 1", act = nil}, 
		["D_D2"] = {text = "Draw 2 and discard 2", act = nil}, 
		["D_D3"] = {text = "Draw 3 and discard 3", act = nil}, 
		["D_W_2D"] = {text = "Discard 1 white, gain 2 dollars", act = nil}, 
		["D_W_4D"] = {text = "Discard 1 white, gain 4 dollars", act = nil}, 
		["D_G_2D"] = {text = "Discard 1 green, gain 2 dollars", act = nil}, 
		["D_B_2D"] = {text = "Discard 1 black, gain 2 dollars", act = nil}, 
		["D_B_2C"] = {text = "Discard 1 black, gain 2 certificate", act = nil}, 
		["D_Y_10D"] = {text = "Discard 1 yellow, gain 10 dollars", act = nil}, 
		["D_P_3D"] = {text = "Discard 1 pair, gain 3 dollars", act = nil}, 
		["D_P_4D"] = {text = "Discard 1 pair, gain 4 dollars", act = nil}, 
		["D_g_2D"] = {text = "Discard 1 grey, gain 2 dollars", act = nil}, 
		["D_g_3D"] = {text = "Discard 1 grey, gain 3 dollars", act = nil}, 
		["D_g_4D"] = {text = "Discard 1 grey, gain 4 dollars", act = nil}, 
		["D_g_1E"] = {text = "Discard 1 grey, engine moves 1 forward", act = nil}, 
		["D_g_1C"] = {text = "Discard 1 grey, gain 1 certificate", act = nil}, 
		["D_g_2C"] = {text = "Discard 1 grey, gain 2 certificate", act = nil}, 
		["D_o_2C"] = {text = "Discard 1 objective card, gain 2 certificate", act = nil}, 
		["D_D_CW"] = {text = "Draw and discard per cowboy", act = nil}, 
		["D_A_1C"] = {text = "Discard any 1 card, gain 1 certificate", act = nil}, 
		["D_A_3D"] = {text = "Discard any 1 card, gain 3 dollars, gain 1 objective card to hand", act = nil}, 
		["MaxC"] = {text = "Max Certificate", act = nil}, 
		["H0"] = {text = "Hire one worker", act = nil}, 
		["H-2"] = {text = "Hire one worker with 2 costs more", act = nil}, 
		["H2"] = {text = "Hire one worker with 2 costs less", act = nil}, 
		["H1"] = {text = "Hire one worker with 1 cost less", act = nil}, 
		["B2"] = {text = "Build with 2 dollars per craftsman", act = nil},
		["B1"] = {text = "Build with 1 dollar per craftsman", act = nil},
		["CorOb"] = {text = "Gain 1 certificate or gain 1 objective card", act = nil},
		["E"] = {text = "Engine moves forward per engineer", act = nil},
		["E1D-1"] = {text = "Pay 1 dollars, engine moves 1 forward", act = nil},
		["E2D-2"] = {text = "Pay 2 dollars, engine moves 2 forward", act = nil},
		["E3"] = {text = "Engine moves 3 forward", act = nil},
		["E4"] = {text = "Engine moves 4 forward", act = nil},
		["E-1_3D"] = {text = "Engine moves 1 backward, gain 3 dollars", act = nil},
		["E-1_D-1_1C"] = {text = "Engine moves 1 backward, pay 1 dollars, gain 1 certificate", act = nil},
		["E-2_D-2_2C"] = {text = "Engine moves 2 backward, pay 2 dollars, gain 2 certificate", act = nil},
		["E-1_R1"] = {text = "Engine moves 1 backward, remove 1 card", act = nil},
		["E-2_R2"] = {text = "Engine moves 2 backward, remove 2 card", act = nil},
		["ED"] = {text = "Gain dollars per engineer", act = nil}, 
		["CM"] = {text = "Visit cattle market", act = nil},
		["HZ7"] = {text = "Remove a hazard (costs 7 dollars)", act = nil},
		["HZ5"] = {text = "Remove a hazard (costs 5 dollars)", act = nil},
		["HZ"] = {text = "Remove a hazard", act = nil},
		["SA"] = {text = "Single auxiliary action", act = nil},
		["DA"] = {text = "Double auxiliary action", act = nil},
		["BD"] = {text = "Gain dollars per bush building", act = nil},
		["BE"] = {text = "Engines moves forward per bush building", act = nil},
		["TPair"] = {text = "2 certificate and 2 dollars per teepee pair", act = nil},
		["TP"] = {text = "Trade with the Indians (gain 1 Teepee)", act = nil},
		["TPorDA"] = {text = "Trade with the Indians (gain 1 Teepee) or Double auxiliary action", act = nil},
		["MV1"] = {text = "Move 1", act = nil},
		["MV2"] = {text = "Move 2", act = nil},
		["MV3"] = {text = "Move 3", act = nil},
		["MV4"] = {text = "Move 4", act = nil},
		["MV5"] = {text = "Move 5", act = nil},
		["MV3F"] = {text = "Move 3 with ignoring fee", act = nil},
		["Del"] = {text = "Extra delivery", act = nil},
		["Copy"] = {text = "Copy action of one adjacent building", act = nil},
		["Up"] = {text = "Upgrade station behind engine", act = nil},

	},
	kc = {
	},
	tileStack = {
	},
	city = {
	}, 
	railroad = {
	}, 
	cattleMarket = {
	}, 
	jobMarket = {
	}, 
	objectiveCard = {
	}, 
	players = {
		player1 = {
			currentManLoc,
			currentEngLoc,
			money, 
			availableBuilding, 
			drawDeck, 
			hand, 
			discardPile, 
			removedCard, 
			objectiveCard,
			hz,
			tp,
			upgrade = { dollar = 1, d_d = 1, cert = 0, engine = 0, remove = 0, move = 0, hand = 0, cert = 0, },
			employee = { cw = 1, cf = 1, eg = 1 },
			cert = 0,
		},
		computer = {
		},
	},
}

return _OBJ

--[[
	MAP_TILE_TYPE = {
		NOTHING = "NOTHING", 
		NEUTRAL_BUILDING = "NEUTRAL_BUILDING", 
		PRIVATE_BUILDING = "PRIVATE_BUILDING", 
		HAZARD = "HAZARD", 
		TEEPEE = "TEEPEE",
	}
--]]
